var appStrings = {
  "welcome": "welcome",
  "Browse categories": "Browse categories",
  "All categories": "All categories",
  "Top services": "Top services",
  "Recently listed": "Recently listed",
  "See all": "See all",
  "Home": "Home",
  "Orders": "Orders",
  "Save": "Save",
  "Saved": "Saved",
  "Search": "Search",
  "Settings": "Settings",
  "Search services": "Search services",
  "Date": "Date",
  "Schedule": "Schedule",
  "Billed": "Billed",
  "My orders": "My orders",
  "Seller Details": "Seller Details",
  "Name": "Name",
  "Email": "Email",
  "Phone": "Phone",
  "Post Code": "Post Code",
  "Address": "Address",
  "Date & Schedule": "Date & Schedule",
  "Amount Details": "Amount Details",
  "Package fee": "Package fee",
  "Extra service": "Extra service",
  "Subtotal": "Subtotal",
  "Tax": "Tax",
  "Total": "Total",
  "Payment status": "Payment status",
  "Order Status": "Order Status",
  "Saved Services": "Saved Services",
  "Starts from": "Starts from",
  "No result found": "No result found",
  "Pending orders": "Pending orders",
  "Active orders": "Active orders",
  "Completed orders": "Completed orders",
  "Total orders": "Total orders",
  "City": "City",
  "Area": "Area",
  "Country": "Country",
  "Support ticket": "Support ticket",
  "Edit profile": "Edit profile",
  "Change Password": "Change Password",
  "Logout": "Logout",
  "Create": "Create",
  "No ticket": "No ticket",
  "All services": "All services",
  "All": "All",
  "Highest price": "Highest price",
  "Lowest price": "Lowest price",
  "Latest service": "Latest service",
  "Full Name": "Full Name",
  "About": "About",
  "Your Address": "Your Address",
  "Choose country": "Choose country",
  "Choose states": "Choose states",
  "Choose Area": "Choose Area",
  "Service Name": "Service Name",
  "Our Package": "Our Package",
  "Orders Completed": "Orders Completed",
  "Seller ratings": "Seller ratings",
  "Overview": "Overview",
  "About Seller": "About Seller",
  "Review": "Review",
  "Benefits of premium Package": "Benefits of premium Package",
  "FAQ": "FAQ",
  "Book appointment": "Book appointment",
  "Personalize": "Personalize",
  "Service personalization": "Service personalization",
  "Next": "Next",
  "What's included": "What's included",
  "Add Extra": "Add Extra",
  "Benefits of the package": "Benefits of the package",
  "Available Schedules": "Available Schedules",
  "Available time": "Available time",
  "No schedule available on this date": "No schedule available on this date",
  "Choose Location": "Choose Location",
  "Booking informations": "Booking informations",
  "Booking confirmation": "Booking confirmation",
  "Booking Details": "Booking Details",
  "Location": "Location",
  "Swipe up for details": "Swipe up for details",
  "Proceed to payment": "Proceed to payment",
  "Collapse details": "Collapse details",
  "Appointment package service": "Appointment package service",
  "Extra service fee": "Extra service fee",
  "Coupon": "Coupon",
  "Coupon code": "Coupon code",
  "Enter coupon code": "Enter coupon code",
  "Apply": "Apply",
  "Payment": "Payment",
  "Total payable": "Total payable",
  "Choose payment method": "Choose payment method",
  "Choose images": "Choose images",
  "I agree with the terms and conditions":
      "I agree with the terms and conditions",
  "Pay & confirm order": "Pay & confirm order",
  "Payment successful": "Payment successful",
  "Order status": "Order status",
  "Are you sure": "Are you sure",
  "Cancel": "Cancel",
  "Welcome back! Login": "Welcome back! Login",
  "Password": "Password",
  "Remember me": "Remember me",
  "Forgot Password?": "Forgot Password?",
  "Login": "Login",
  "Enter password": "Enter password",
  "Do not have an account": "Do not have an account",
  "Register": "Register",
  "Or": "Or",
  "Login with google": "Login with google",
  "Login with facebook": "Login with facebook",
  "Register to join us": "Register to join us",
  "Enter your full name": "Enter your full name",
  "Enter your username": "Enter your username",
  "Enter your email": "Enter your email",
  "Continue": "Continue",
  "Already have an account": "Already have an account",
  "Repeat password": "Repeat password",
  "Phone number": "Phone number",
  "Reset password": "Reset password",
  "Enter the email you used to create account and we well send information for resetting password":
      "Enter the email you used to create account and we well send information for resetting password",
  "Enter email": "Enter email",
  "Send instructions": "Send instructions",
  "Enter the 4 digit code": "Enter the 4 digit code",
  "Enter the 4 digit code we sent to your email in order to reset password":
      "Enter the 4 digit code we sent to your email in order to reset password",
  "Did not receive": "Didn't receive",
  "Send again": "Send again",
  "Something went wrong": "Something went wrong",
  "Please wait while the profile is updating":
      "Please wait while the profile is updating",
  "Please enter your email": "Please enter your email",
  "Please enter post code": "Please enter post code",
  "You must select a state and area": "You must select a state and area",
  "Address field is required": "Address field is required",
  "Phone field is required": "Phone field is required",
  "Updating profile...It may take few seconds":
      "Updating profile...It may take few seconds",
  "You must agree with the terms and conditions to register":
      "You must agree with the terms and conditions to register",
  "Password did not match": "Password did not match",
  "Password must be at least 6 characters":
      "Password must be at least 6 characters",
  "Have an account": "Have an account",
};
